### ISSUE TITLE
google sign in - using firebase

### ISSUE THREAD

**Issue by tanishksahni** [tanishksahni/user_auth#3]
On branch firebase  - Apply google sign-in method using firebase

**Comment by Yaswanth-Mitta** [comment]
Hey @tanishksahni  Can i work on it?

**Comment by tanishksahni** [comment]
Yeah sure @Yaswanth-Mitta  !
Let's discuss it and then go for it.

**Comment by Yaswanth-Mitta** [comment]
okk

**Comment by tanishksahni** [comment]
@Yaswanth-Mitta 
You can fork the repository from branch - firebase. 
Read the Hactoberfest.md and README.md. For any issue do contact.

**Comment by tanishksahni** [comment]
branch to add your commits 
git fetch origin
git checkout 3-google-sign-in-using-firebase

**Comment by Yaswanth-Mitta** [comment]
hey @tanishksahni  sorry to say that i  cant  contribute to this because i am working on another project which uses different flutter sdk version.

**Comment by tanishksahni** [comment]
@Yaswanth-Mitta no issue with that. All the best!
